services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 8080:8080
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
 
volumes:
  pgdata: